language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'
branches:
  only:
    - 'master'
jobs:
  include:
    - stage: release
      node_js: '10'
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - 'yarn release'
